apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspect-services
  namespace: defaults
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - services
    verbs:
      - get
      - watch
      - list
